### ISSUE TITLE
Add maximum candidates option

### ISSUE THREAD

**Issue by matlink** [Cynosureprime/chasm#3]
Is it possible to add a command line option to output only the first `N` words? 
It is useful for example for speed benchmarking.
Thanks :grinning:

**Comment by hops** [comment]
It's not that easy, let me explain.
chasm stores the splitted words in JudySL arrays (one for each split character times two, left and right side). They are kept in memory until the full input list is processed and the candidates are written to disk.
Therefore limiting the output is not useful for a speed benchmark because the input list will be processed fully.
For a benchmark you could limit the input list and since chasm reads from stdin you can already achieve that like this:
`head -n 100000 yourlist.txt | chasm -options...`

I hope it makes sense.

**Comment by matlink** [comment]
Understood, that's sad :(
